{% set name = "azure-mgmt-containerservice" %}
{% set version = "41.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 9830d0a42730609c97a133a913e2caffbd163d4d3ff315afc3a76728222a3f61

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=77.0.3
  run:
    - python
    - isodate >=0.6.1
    - azure-mgmt-core >=1.6.0
    - typing-extensions >=4.6.0

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.containerservice
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Container Service Management Client Library for Python.
  description: |
    This is the Microsoft Azure Container Service Management Client Library.
  doc_url: https://github.com/Azure/azure-sdk-for-python
  dev_url: https://github.com/Azure/azure-sdk-for-python


extra:
  recipe-maintainers:
    - tim-werner
